"""审方规则库增加相互作用字段

Revision ID: a95862fe8c3f
Revises: c1627502ad43
Create Date: 2026-08-10 10:54:06.340516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95862fe8c3f'
down_revision: Union[str, Sequence[str], None] = 'c1627502ad43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 存量行以空串填充，保证非空约束可加
    op.add_column(
        'drug_rules',
        sa.Column('interactions', sa.String(length=512), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drug_rules', 'interactions')
    # ### end Alembic commands ###
