"""初始基线：对齐第一阶段全部模型

Revision ID: c1627502ad43
Revises: 
Create Date: 2026-08-10 10:41:21.891438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1627502ad43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_systems_code'), 'code_systems', ['code'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('course_type', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('speaker', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_code', sa.String(length=64), nullable=False),
    sa.Column('max_daily_dose', sa.Float(), nullable=False),
    sa.Column('dose_unit', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_rules_drug_code'), 'drug_rules', ['drug_code'], unique=True)
    op.create_table('duty_rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_type', sa.String(length=16), nullable=False),
    sa.Column('duty_date', sa.String(length=10), nullable=False),
    sa.Column('shift', sa.String(length=16), nullable=False),
    sa.Column('doctor_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_rosters_center_type'), 'duty_rosters', ['center_type'], unique=False)
    op.create_index(op.f('ix_duty_rosters_duty_date'), 'duty_rosters', ['duty_date'], unique=False)
    op.create_table('health_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_articles_status'), 'health_articles', ['status'], unique=False)
    op.create_table('official_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('body', sa.String(length=4096), nullable=False),
    sa.Column('issuer', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_docs_status'), 'official_docs', ['status'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('org_type', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ehc_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id_card', sa.String(length=18), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('birth_date', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_card', name='uq_patient_id_card')
    )
    op.create_index(op.f('ix_patients_ehc_no'), 'patients', ['ehc_no'], unique=True)
    op.create_index(op.f('ix_patients_id_card'), 'patients', ['id_card'], unique=False)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_table('ph_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('level', sa.String(length=4), nullable=False),
    sa.Column('disease_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ph_events_status'), 'ph_events', ['status'], unique=False)
    op.create_table('qc_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_type', sa.String(length=16), nullable=False),
    sa.Column('item', sa.String(length=128), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=False),
    sa.Column('record_date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_records_center_type'), 'qc_records', ['center_type'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('content', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_templates_center_type'), 'report_templates', ['center_type'], unique=False)
    op.create_table('tcm_techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('indication', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('appointment_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('appointment_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=16), nullable=False),
    sa.Column('resource_name', sa.String(length=128), nullable=False),
    sa.Column('slot_date', sa.String(length=10), nullable=False),
    sa.Column('slot_time', sa.String(length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_slots_org_id'), 'appointment_slots', ['org_id'], unique=False)
    op.create_index(op.f('ix_appointment_slots_slot_date'), 'appointment_slots', ['slot_date'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_assets_org_id'), 'assets', ['org_id'], unique=False)
    op.create_table('child_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('birth_date', sa.String(length=10), nullable=False),
    sa.Column('guardian_patient_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chronic_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('disease', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('managed_by_org_id', sa.Integer(), nullable=False),
    sa.Column('next_due', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['managed_by_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'disease', name='uq_chronic_patient_disease')
    )
    op.create_index(op.f('ix_chronic_patients_disease'), 'chronic_patients', ['disease'], unique=False)
    op.create_index(op.f('ix_chronic_patients_level'), 'chronic_patients', ['level'], unique=False)
    op.create_index(op.f('ix_chronic_patients_patient_id'), 'chronic_patients', ['patient_id'], unique=False)
    op.create_table('code_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['code_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'code', name='uq_entry_system_code')
    )
    op.create_index(op.f('ix_code_entries_code'), 'code_entries', ['code'], unique=False)
    op.create_index(op.f('ix_code_entries_name'), 'code_entries', ['name'], unique=False)
    op.create_index(op.f('ix_code_entries_system_id'), 'code_entries', ['system_id'], unique=False)
    op.create_table('consult_experts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=64), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('drug_shortages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('drug_code', sa.String(length=64), nullable=False),
    sa.Column('drug_name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_shortages_org_id'), 'drug_shortages', ['org_id'], unique=False)
    op.create_index(op.f('ix_drug_shortages_status'), 'drug_shortages', ['status'], unique=False)
    op.create_table('drug_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('drug_code', sa.String(length=64), nullable=False),
    sa.Column('drug_name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'drug_code', name='uq_stock_org_drug')
    )
    op.create_index(op.f('ix_drug_stocks_drug_code'), 'drug_stocks', ['drug_code'], unique=False)
    op.create_index(op.f('ix_drug_stocks_org_id'), 'drug_stocks', ['org_id'], unique=False)
    op.create_table('elderly_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('adl_score', sa.Integer(), nullable=False),
    sa.Column('cognitive_score', sa.Integer(), nullable=False),
    sa.Column('tcm_constitution', sa.String(length=32), nullable=False),
    sa.Column('care_level', sa.String(length=16), nullable=False),
    sa.Column('assessed_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elderly_assessments_patient_id'), 'elderly_assessments', ['patient_id'], unique=False)
    op.create_table('emergency_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('caller_phone', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('symptom', sa.String(length=512), nullable=False),
    sa.Column('ambulance_no', sa.String(length=32), nullable=False),
    sa.Column('dest_org_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dest_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_cases_status'), 'emergency_cases', ['status'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_org_id'), 'employees', ['org_id'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=64), nullable=False),
    sa.Column('encounter_type', sa.String(length=16), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=64), nullable=False),
    sa.Column('diagnosis_name', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_org_id'), 'encounters', ['org_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_table('fd_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=64), nullable=False),
    sa.Column('package', sa.String(length=16), nullable=False),
    sa.Column('signed_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'org_id', name='uq_contract_patient_org')
    )
    op.create_index(op.f('ix_fd_contracts_org_id'), 'fd_contracts', ['org_id'], unique=False)
    op.create_index(op.f('ix_fd_contracts_patient_id'), 'fd_contracts', ['patient_id'], unique=False)
    op.create_table('finance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=8), nullable=False),
    sa.Column('item', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_entries_org_id'), 'finance_entries', ['org_id'], unique=False)
    op.create_index(op.f('ix_finance_entries_period'), 'finance_entries', ['period'], unique=False)
    op.create_table('health_monitor_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=16), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('exceeded', sa.Boolean(), nullable=False),
    sa.Column('record_date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_monitor_records_domain'), 'health_monitor_records', ['domain'], unique=False)
    op.create_index(op.f('ix_health_monitor_records_exceeded'), 'health_monitor_records', ['exceeded'], unique=False)
    op.create_table('infectious_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('disease_code', sa.String(length=64), nullable=False),
    sa.Column('disease_name', sa.String(length=128), nullable=False),
    sa.Column('onset_date', sa.String(length=10), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infectious_cases_disease_code'), 'infectious_cases', ['disease_code'], unique=False)
    op.create_index(op.f('ix_infectious_cases_onset_date'), 'infectious_cases', ['onset_date'], unique=False)
    op.create_index(op.f('ix_infectious_cases_org_id'), 'infectious_cases', ['org_id'], unique=False)
    op.create_table('insurance_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('settle_type', sa.String(length=16), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('insurance_pay', sa.Float(), nullable=False),
    sa.Column('self_pay', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_settlements_org_id'), 'insurance_settlements', ['org_id'], unique=False)
    op.create_index(op.f('ix_insurance_settlements_patient_id'), 'insurance_settlements', ['patient_id'], unique=False)
    op.create_table('maternal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('lmp', sa.String(length=10), nullable=False),
    sa.Column('edc', sa.String(length=10), nullable=False),
    sa.Column('gravidity', sa.Integer(), nullable=False),
    sa.Column('parity', sa.Integer(), nullable=False),
    sa.Column('high_risk', sa.Boolean(), nullable=False),
    sa.Column('risk_factors', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', name='uq_maternal_patient')
    )
    op.create_index(op.f('ix_maternal_records_patient_id'), 'maternal_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_maternal_records_status'), 'maternal_records', ['status'], unique=False)
    op.create_table('medical_wastes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('waste_type', sa.String(length=16), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('handler_name', sa.String(length=64), nullable=False),
    sa.Column('collected_date', sa.String(length=10), nullable=False),
    sa.Column('handed_over_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_wastes_collected_date'), 'medical_wastes', ['collected_date'], unique=False)
    op.create_index(op.f('ix_medical_wastes_org_id'), 'medical_wastes', ['org_id'], unique=False)
    op.create_index(op.f('ix_medical_wastes_status'), 'medical_wastes', ['status'], unique=False)
    op.create_table('ph_event_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=512), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ph_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ph_event_actions_event_id'), 'ph_event_actions', ['event_id'], unique=False)
    op.create_table('satisfaction_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satisfaction_surveys_target_type'), 'satisfaction_surveys', ['target_type'], unique=False)
    op.create_table('special_disease_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_disease_apps_patient_id'), 'special_disease_apps', ['patient_id'], unique=False)
    op.create_table('sterilization_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=32), nullable=False),
    sa.Column('center_org_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dispatched_to_org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['center_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['dispatched_to_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sterilization_batches_batch_no'), 'sterilization_batches', ['batch_no'], unique=True)
    op.create_index(op.f('ix_sterilization_batches_status'), 'sterilization_batches', ['status'], unique=False)
    op.create_table('tcm_dispense_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('from_org_id', sa.Integer(), nullable=False),
    sa.Column('herbs', sa.String(length=1024), nullable=False),
    sa.Column('doses', sa.Integer(), nullable=False),
    sa.Column('decoct', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcm_dispense_orders_patient_id'), 'tcm_dispense_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tcm_dispense_orders_status'), 'tcm_dispense_orders', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vaccination_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_code', sa.String(length=64), nullable=False),
    sa.Column('vaccine_name', sa.String(length=128), nullable=False),
    sa.Column('dose_no', sa.Integer(), nullable=False),
    sa.Column('vaccinated_date', sa.String(length=10), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccination_records_patient_id'), 'vaccination_records', ['patient_id'], unique=False)
    op.create_table('vaccine_contraindications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_code', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccine_contraindications_patient_id'), 'vaccine_contraindications', ['patient_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id', 'patient_id', name='uq_appointment_slot_patient')
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_slot_id'), 'appointments', ['slot_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_path'), 'audit_logs', ['path'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_table('child_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('visit_type', sa.String(length=16), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=False),
    sa.Column('visit_date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_visits_child_id'), 'child_visits', ['child_id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('from_org_id', sa.Integer(), nullable=False),
    sa.Column('to_org_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expert_name', sa.String(length=64), nullable=False),
    sa.Column('opinion', sa.String(length=2048), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['to_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    op.create_table('cssd_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['sterilization_batches.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cssd_requests_org_id'), 'cssd_requests', ['org_id'], unique=False)
    op.create_index(op.f('ix_cssd_requests_status'), 'cssd_requests', ['status'], unique=False)
    op.create_table('emergency_vitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('sbp', sa.Float(), nullable=True),
    sa.Column('dbp', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['emergency_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_vitals_case_id'), 'emergency_vitals', ['case_id'], unique=False)
    op.create_table('exam_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('from_org_id', sa.Integer(), nullable=False),
    sa.Column('center_type', sa.String(length=16), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('clinical_info', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('recognized_from_id', sa.Integer(), nullable=True),
    sa.Column('recognition_declined_reason', sa.String(length=256), nullable=False),
    sa.Column('sample_status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recognized_from_id'], ['exam_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_requests_center_type'), 'exam_requests', ['center_type'], unique=False)
    op.create_index(op.f('ix_exam_requests_item_code'), 'exam_requests', ['item_code'], unique=False)
    op.create_index(op.f('ix_exam_requests_patient_id'), 'exam_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_exam_requests_status'), 'exam_requests', ['status'], unique=False)
    op.create_table('fd_contract_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['fd_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fd_contract_services_contract_id'), 'fd_contract_services', ['contract_id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chronic_id', sa.Integer(), nullable=False),
    sa.Column('sbp', sa.Float(), nullable=True),
    sa.Column('dbp', sa.Float(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('guidance', sa.String(length=1024), nullable=False),
    sa.Column('next_due', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chronic_id'], ['chronic_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_chronic_id'), 'followups', ['chronic_id'], unique=False)
    op.create_table('maternal_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('visit_type', sa.String(length=16), nullable=False),
    sa.Column('gest_week', sa.Integer(), nullable=True),
    sa.Column('bp', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=False),
    sa.Column('visit_date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['maternal_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maternal_visits_record_id'), 'maternal_visits', ['record_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('review_comment', sa.String(length=1024), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_status'), 'prescriptions', ['status'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('from_org_id', sa.Integer(), nullable=False),
    sa.Column('to_org_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['to_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('secondments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('from_org_id', sa.Integer(), nullable=False),
    sa.Column('to_org_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['from_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['to_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secondments_employee_id'), 'secondments', ['employee_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_code', sa.String(length=64), nullable=False),
    sa.Column('from_org_id', sa.Integer(), nullable=False),
    sa.Column('to_org_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['to_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_training_course_user')
    )
    op.create_index(op.f('ix_training_records_course_id'), 'training_records', ['course_id'], unique=False)
    op.create_index(op.f('ix_training_records_user_id'), 'training_records', ['user_id'], unique=False)
    op.create_table('exam_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('finding', sa.String(length=2048), nullable=False),
    sa.Column('conclusion', sa.String(length=1024), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('reported_by', sa.String(length=64), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['exam_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_reports_request_id'), 'exam_reports', ['request_id'], unique=True)
    op.create_table('online_consults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('consult_type', sa.String(length=16), nullable=False),
    sa.Column('question', sa.String(length=1024), nullable=False),
    sa.Column('reply', sa.String(length=2048), nullable=False),
    sa.Column('doctor_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_online_consults_patient_id'), 'online_consults', ['patient_id'], unique=False)
    op.create_index(op.f('ix_online_consults_status'), 'online_consults', ['status'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('drug_code', sa.String(length=64), nullable=False),
    sa.Column('drug_name', sa.String(length=128), nullable=False),
    sa.Column('daily_dose', sa.Float(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    op.create_table('referral_certs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('cert_no', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_no'),
    sa.UniqueConstraint('referral_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_certs')
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_online_consults_status'), table_name='online_consults')
    op.drop_index(op.f('ix_online_consults_patient_id'), table_name='online_consults')
    op.drop_table('online_consults')
    op.drop_index(op.f('ix_exam_reports_request_id'), table_name='exam_reports')
    op.drop_table('exam_reports')
    op.drop_index(op.f('ix_training_records_user_id'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_course_id'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_secondments_employee_id'), table_name='secondments')
    op.drop_table('secondments')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_prescriptions_status'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_maternal_visits_record_id'), table_name='maternal_visits')
    op.drop_table('maternal_visits')
    op.drop_index(op.f('ix_followups_chronic_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_fd_contract_services_contract_id'), table_name='fd_contract_services')
    op.drop_table('fd_contract_services')
    op.drop_index(op.f('ix_exam_requests_status'), table_name='exam_requests')
    op.drop_index(op.f('ix_exam_requests_patient_id'), table_name='exam_requests')
    op.drop_index(op.f('ix_exam_requests_item_code'), table_name='exam_requests')
    op.drop_index(op.f('ix_exam_requests_center_type'), table_name='exam_requests')
    op.drop_table('exam_requests')
    op.drop_index(op.f('ix_emergency_vitals_case_id'), table_name='emergency_vitals')
    op.drop_table('emergency_vitals')
    op.drop_index(op.f('ix_cssd_requests_status'), table_name='cssd_requests')
    op.drop_index(op.f('ix_cssd_requests_org_id'), table_name='cssd_requests')
    op.drop_table('cssd_requests')
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_child_visits_child_id'), table_name='child_visits')
    op.drop_table('child_visits')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_path'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_appointments_slot_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_vaccine_contraindications_patient_id'), table_name='vaccine_contraindications')
    op.drop_table('vaccine_contraindications')
    op.drop_index(op.f('ix_vaccination_records_patient_id'), table_name='vaccination_records')
    op.drop_table('vaccination_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tcm_dispense_orders_status'), table_name='tcm_dispense_orders')
    op.drop_index(op.f('ix_tcm_dispense_orders_patient_id'), table_name='tcm_dispense_orders')
    op.drop_table('tcm_dispense_orders')
    op.drop_index(op.f('ix_sterilization_batches_status'), table_name='sterilization_batches')
    op.drop_index(op.f('ix_sterilization_batches_batch_no'), table_name='sterilization_batches')
    op.drop_table('sterilization_batches')
    op.drop_index(op.f('ix_special_disease_apps_patient_id'), table_name='special_disease_apps')
    op.drop_table('special_disease_apps')
    op.drop_index(op.f('ix_satisfaction_surveys_target_type'), table_name='satisfaction_surveys')
    op.drop_table('satisfaction_surveys')
    op.drop_index(op.f('ix_ph_event_actions_event_id'), table_name='ph_event_actions')
    op.drop_table('ph_event_actions')
    op.drop_index(op.f('ix_medical_wastes_status'), table_name='medical_wastes')
    op.drop_index(op.f('ix_medical_wastes_org_id'), table_name='medical_wastes')
    op.drop_index(op.f('ix_medical_wastes_collected_date'), table_name='medical_wastes')
    op.drop_table('medical_wastes')
    op.drop_index(op.f('ix_maternal_records_status'), table_name='maternal_records')
    op.drop_index(op.f('ix_maternal_records_patient_id'), table_name='maternal_records')
    op.drop_table('maternal_records')
    op.drop_index(op.f('ix_insurance_settlements_patient_id'), table_name='insurance_settlements')
    op.drop_index(op.f('ix_insurance_settlements_org_id'), table_name='insurance_settlements')
    op.drop_table('insurance_settlements')
    op.drop_index(op.f('ix_infectious_cases_org_id'), table_name='infectious_cases')
    op.drop_index(op.f('ix_infectious_cases_onset_date'), table_name='infectious_cases')
    op.drop_index(op.f('ix_infectious_cases_disease_code'), table_name='infectious_cases')
    op.drop_table('infectious_cases')
    op.drop_index(op.f('ix_health_monitor_records_exceeded'), table_name='health_monitor_records')
    op.drop_index(op.f('ix_health_monitor_records_domain'), table_name='health_monitor_records')
    op.drop_table('health_monitor_records')
    op.drop_index(op.f('ix_finance_entries_period'), table_name='finance_entries')
    op.drop_index(op.f('ix_finance_entries_org_id'), table_name='finance_entries')
    op.drop_table('finance_entries')
    op.drop_index(op.f('ix_fd_contracts_patient_id'), table_name='fd_contracts')
    op.drop_index(op.f('ix_fd_contracts_org_id'), table_name='fd_contracts')
    op.drop_table('fd_contracts')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_org_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_org_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_emergency_cases_status'), table_name='emergency_cases')
    op.drop_table('emergency_cases')
    op.drop_index(op.f('ix_elderly_assessments_patient_id'), table_name='elderly_assessments')
    op.drop_table('elderly_assessments')
    op.drop_index(op.f('ix_drug_stocks_org_id'), table_name='drug_stocks')
    op.drop_index(op.f('ix_drug_stocks_drug_code'), table_name='drug_stocks')
    op.drop_table('drug_stocks')
    op.drop_index(op.f('ix_drug_shortages_status'), table_name='drug_shortages')
    op.drop_index(op.f('ix_drug_shortages_org_id'), table_name='drug_shortages')
    op.drop_table('drug_shortages')
    op.drop_table('consult_experts')
    op.drop_index(op.f('ix_code_entries_system_id'), table_name='code_entries')
    op.drop_index(op.f('ix_code_entries_name'), table_name='code_entries')
    op.drop_index(op.f('ix_code_entries_code'), table_name='code_entries')
    op.drop_table('code_entries')
    op.drop_index(op.f('ix_chronic_patients_patient_id'), table_name='chronic_patients')
    op.drop_index(op.f('ix_chronic_patients_level'), table_name='chronic_patients')
    op.drop_index(op.f('ix_chronic_patients_disease'), table_name='chronic_patients')
    op.drop_table('chronic_patients')
    op.drop_table('child_records')
    op.drop_index(op.f('ix_assets_org_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_appointment_slots_slot_date'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_org_id'), table_name='appointment_slots')
    op.drop_table('appointment_slots')
    op.drop_table('appointment_blacklist')
    op.drop_table('tcm_techniques')
    op.drop_index(op.f('ix_report_templates_center_type'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_qc_records_center_type'), table_name='qc_records')
    op.drop_table('qc_records')
    op.drop_index(op.f('ix_ph_events_status'), table_name='ph_events')
    op.drop_table('ph_events')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_id_card'), table_name='patients')
    op.drop_index(op.f('ix_patients_ehc_no'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_official_docs_status'), table_name='official_docs')
    op.drop_table('official_docs')
    op.drop_index(op.f('ix_health_articles_status'), table_name='health_articles')
    op.drop_table('health_articles')
    op.drop_index(op.f('ix_duty_rosters_duty_date'), table_name='duty_rosters')
    op.drop_index(op.f('ix_duty_rosters_center_type'), table_name='duty_rosters')
    op.drop_table('duty_rosters')
    op.drop_index(op.f('ix_drug_rules_drug_code'), table_name='drug_rules')
    op.drop_table('drug_rules')
    op.drop_table('courses')
    op.drop_index(op.f('ix_code_systems_code'), table_name='code_systems')
    op.drop_table('code_systems')
    # ### end Alembic commands ###
