"""重构安全网：端点 URL 集合 与 模型名字集合 的**零漂移**守卫。

ADR-0006（倾倒场路由回归业务前缀）与 ADR-0008（God 文件分域拆包）都是
"只搬不改"的重构——搬完之后对外必须**一个字节都不差**。这两条用例是那把尺子：

- **端点集合**：快照全部 `method + path`。搬路由时漏掉一个、或不小心改了 path，
  这里立刻红。ADR-0006 明写"没有这道网，搬漏一个端点不会有人发现"。
- **模型名字集合**：快照 `Base` 注册表里全部 ORM 类名。拆 `models.py` 成包时
  若漏了一个类没在 `__init__.py` 重导出，它就不再注册进 `Base.metadata`——
  **建表会静默少一张**，而不是报错。

两份快照**允许随功能增删而更新**，但更新必须是**刻意的**：改这两个常量的 PR
要说清"为什么这个端点/模型该增该减"。这与契约棘轮的"只进不退"不同——
那个是欠账只许变小，这个是"变了要有人签字"。

## 关于遍历方式

端点从**运行期的 app** 取，因为那才是外部真正打得到的面（源码里定义了却没
`include_router` 的路由不算数）。代价是要穿过 FastAPI 的运行期封装——本仓库
当前版本把 `include_router` 的结果存成 `_IncludedRouter`，`app.routes` 上直接
`isinstance(APIRoute)` 只能捞到 4 条。写这个守卫时就先踩了一次：遍历写错、
快照只存下 1 个端点，用例照样绿——**一个永远不会红的守卫比没有守卫更糟**。
所以下面额外加了 `test_遍历本身没瞎`：数量低于下限直接失败，
遍历方式将来被 FastAPI 改坏时会先炸在这里，而不是悄悄放行。
"""
from pathlib import Path

from fastapi import APIRouter
from fastapi.routing import APIRoute

from app.database import Base
from app.main import app

#: 端点数量下限。用途不是钉死数字（增删端点是正常的），而是**防止遍历失效**：
#: 真实规模是 800+，若某次遍历只捞到几条，说明穿封装的方式失效了。
MIN_SANE_ENDPOINTS = 800

#: 当前 /api 端点快照（893 个）。由真实应用生成，勿手写。
#: 工程包 I1 新增 8 个：HL7 ADT/ORU 入站、FHIR DiagnosticReport/Encounter 入站、
#: 传染病/死因报告卡导出（单卡 JSON + 批量 CSV）。
SNAPSHOT_ENDPOINTS = {
    "DELETE /api/analytics/formulas/{key}",
    "DELETE /api/appointments/blacklist/{patient_id}",
    "DELETE /api/dataquality/rules/{rule_id}",
    "DELETE /api/medwaste/locations/{location_id}",
    "DELETE /api/org-groups/{group_id}/members/{org_id}",
    "DELETE /api/portal/me/family/{member_id}",
    "DELETE /api/prescriptions/rules/{drug_code}",
    "DELETE /api/rbac/roles/{role_id}",
    "DELETE /api/rbac/roles/{role_id}/permissions/{permission_id}",
    "DELETE /api/rules/{key}",
    "DELETE /api/spd/groups/{group_id}/members/{patient_id}",
    "DELETE /api/spd/path-nodes/{node_id}",
    "DELETE /api/spd/path-templates/{template_id}",
    "DELETE /api/spd/report-tasks/{task_id}",
    "DELETE /api/spd/team-members/{member_id}",
    "GET /api/access-logs",
    "GET /api/access-logs/mine",
    "GET /api/access-logs/stats",
    "GET /api/accounting/consolidated-statements",
    "GET /api/accounting/subjects",
    "GET /api/accounting/trial-balance",
    "GET /api/accounting/vouchers",
    "GET /api/accounting/vouchers/{voucher_id}",
    "GET /api/analytics/drug-use",
    "GET /api/analytics/efficiency",
    "GET /api/analytics/formula-variables",
    "GET /api/analytics/formulas",
    "GET /api/analytics/outbound-visits",
    "GET /api/analytics/patient-flow",
    "GET /api/analytics/performance-report",
    "GET /api/appointments",
    "GET /api/appointments/blacklist",
    "GET /api/appointments/doctors",
    "GET /api/appointments/slots",
    "GET /api/archive/{ehc_no}",
    "GET /api/attachments",
    "GET /api/attachments/{attachment_id}",
    "GET /api/audit",
    "GET /api/audit/export",
    "GET /api/audit/stats",
    "GET /api/audit/verify",
    "GET /api/billing/charge-items",
    "GET /api/billing/charge-items/{item_id}/price-history",
    "GET /api/billing/details",
    "GET /api/billing/payments",
    "GET /api/billing/reconciliation",
    "GET /api/billing/settlements",
    "GET /api/billing/stats",
    "GET /api/blood/requests",
    "GET /api/blood/stocks",
    "GET /api/certs",
    "GET /api/certs/death-report-cards/export.csv",
    "GET /api/certs/stats",
    "GET /api/certs/{cert_id}/death-report-card",
    "GET /api/checkups",
    "GET /api/checkups/abnormal",
    "GET /api/chronic",
    "GET /api/chronic/disease-types",
    "GET /api/chronic/overdue",
    "GET /api/chronic/{chronic_id}/followups",
    "GET /api/chronic/{chronic_id}/risk",
    "GET /api/consultations",
    "GET /api/consultations/experts",
    "GET /api/consultations/stats",
    "GET /api/contracts",
    "GET /api/contracts/{contract_id}/services",
    "GET /api/cost/allocation-rules",
    "GET /api/cost/departments",
    "GET /api/cost/unit-cost",
    "GET /api/credentials",
    "GET /api/credentials/lookup/{credential_no}",
    "GET /api/credentials/resolve",
    "GET /api/cssd/batches",
    "GET /api/cssd/cost-items",
    "GET /api/cssd/cost-stats",
    "GET /api/cssd/requests",
    "GET /api/dataquality/rules",
    "GET /api/dataquality/run",
    "GET /api/dataquality/summary",
    "GET /api/dictionaries/{system_code}/entries",
    "GET /api/disease-programs",
    "GET /api/disease-programs/enrollments",
    "GET /api/disease-programs/enrollments/{enrollment_id}",
    "GET /api/disease-programs/{program_id}/stats",
    "GET /api/drgs/groups",
    "GET /api/drgs/in-stay-alerts",
    "GET /api/drgs/stats",
    "GET /api/education/courses",
    "GET /api/education/courses/{course_id}/materials",
    "GET /api/education/courses/{course_id}/stats",
    "GET /api/education/live-sessions",
    "GET /api/education/live-sessions/{session_id}/feedback",
    "GET /api/education/material-stats",
    "GET /api/education/my-records",
    "GET /api/education/training-plans",
    "GET /api/education/training-plans/{plan_id}/assessments",
    "GET /api/education/training-plans/{plan_id}/enrollments",
    "GET /api/eldercare/alerts",
    "GET /api/eldercare/assessments",
    "GET /api/eldercare/disabled",
    "GET /api/eldercare/stats",
    "GET /api/emergency/cases",
    "GET /api/emergency/cases/{case_id}/timeline",
    "GET /api/emergency/cases/{case_id}/vitals",
    "GET /api/encounters",
    "GET /api/esb/endpoints",
    "GET /api/esb/flow-runs",
    "GET /api/esb/flows",
    "GET /api/esb/messages",
    "GET /api/esb/stats",
    "GET /api/exams",
    "GET /api/exams/critical",
    "GET /api/exams/critical/unacknowledged",
    "GET /api/exams/recognition-check",
    "GET /api/exams/recognition-items",
    "GET /api/exams/recognition-stats",
    "GET /api/exams/reports/{report_id}/critical-actions",
    "GET /api/exams/reports/{report_id}/revisions",
    "GET /api/exams/resources",
    "GET /api/exams/templates",
    "GET /api/followups",
    "GET /api/followups/overdue",
    "GET /api/followups/stats",
    "GET /api/fund/formula-variables",
    "GET /api/fund/pools",
    "GET /api/fund/pools/{pool_id}/distributions",
    "GET /api/fund/pools/{pool_id}/periods",
    "GET /api/fund/pools/{pool_id}/prepayments",
    "GET /api/fund/pools/{pool_id}/settlement",
    "GET /api/health",
    "GET /api/homevisits",
    "GET /api/homevisits/stats",
    "GET /api/infectious/alerts",
    "GET /api/infectious/cases",
    "GET /api/infectious/cases/export.csv",
    "GET /api/infectious/cases/{case_id}/report-card",
    "GET /api/infectious/diseases",
    "GET /api/infectious/late-reports",
    "GET /api/inpatient/admissions",
    "GET /api/inpatient/admissions/{admission_id}/case-summary",
    "GET /api/inpatient/admissions/{admission_id}/document-completeness",
    "GET /api/inpatient/admissions/{admission_id}/nursing-records",
    "GET /api/inpatient/admissions/{admission_id}/progress-notes",
    "GET /api/inpatient/admissions/{admission_id}/vitals",
    "GET /api/inpatient/beds",
    "GET /api/inpatient/handovers",
    "GET /api/inpatient/orders",
    "GET /api/inpatient/stats",
    "GET /api/inpatient/wards",
    "GET /api/insurance/dual-channel",
    "GET /api/insurance/fund-stats",
    "GET /api/insurance/settlements",
    "GET /api/insurance/special-diseases",
    "GET /api/integration/exchange-logs",
    "GET /api/integration/fhir/Patient/{ehc_no}",
    "GET /api/jobs",
    "GET /api/jobs/runs",
    "GET /api/knowledge",
    "GET /api/knowledge/expiring",
    "GET /api/materials/consumables",
    "GET /api/materials/consumables/trace/{barcode}",
    "GET /api/materials/purchases",
    "GET /api/maternal/children",
    "GET /api/maternal/children/high-risk",
    "GET /api/maternal/children/{child_id}/screenings",
    "GET /api/maternal/records",
    "GET /api/maternal/records/{record_id}/delivery",
    "GET /api/maternal/screening-stats",
    "GET /api/maternal/screenings",
    "GET /api/maternal/women-health",
    "GET /api/medication/profile/{patient_id}",
    "GET /api/medication/shortages",
    "GET /api/medication/shortages/stats",
    "GET /api/medication/supply-risk",
    "GET /api/medication/usage-stats",
    "GET /api/medwaste",
    "GET /api/medwaste/alerts",
    "GET /api/medwaste/handler-stats",
    "GET /api/medwaste/locations",
    "GET /api/medwaste/trace/{trace_code}",
    "GET /api/metrics/alerts",
    "GET /api/metrics/drilldown",
    "GET /api/metrics/drilldown-metrics",
    "GET /api/metrics/overview",
    "GET /api/metrics/trends",
    "GET /api/mgmt/assets",
    "GET /api/mgmt/assets/{asset_id}/movements",
    "GET /api/mgmt/budgets/execution",
    "GET /api/mgmt/departments",
    "GET /api/mgmt/docs",
    "GET /api/mgmt/employees",
    "GET /api/mgmt/employees/{employee_id}/changes",
    "GET /api/mgmt/finance/summary",
    "GET /api/mgmt/params",
    "GET /api/mgmt/payroll",
    "GET /api/mgmt/qc",
    "GET /api/mgmt/rosters",
    "GET /api/mgmt/secondments/stats",
    "GET /api/mgmt/staff-contracts",
    "GET /api/mgmt/staff-contracts/expiring",
    "GET /api/monitor/api-stats",
    "GET /api/monitor/nodes",
    "GET /api/monitor/overview",
    "GET /api/notifications",
    "GET /api/notifications/unread-count",
    "GET /api/org-groups",
    "GET /api/org-groups/coverage",
    "GET /api/org-groups/of-org/{org_id}",
    "GET /api/org-groups/{group_id}/members",
    "GET /api/organizations",
    "GET /api/organizations/tree-health",
    "GET /api/outpatient/consent-templates",
    "GET /api/outpatient/consents",
    "GET /api/outpatient/encounters/{encounter_id}/completeness",
    "GET /api/outpatient/encounters/{encounter_id}/nursing-records",
    "GET /api/outpatient/encounters/{encounter_id}/treatments",
    "GET /api/outpatient/treatments",
    "GET /api/pathology/specimen-stats",
    "GET /api/pathology/specimens",
    "GET /api/consents",
    "GET /api/consents/corrections",
    "GET /api/consents/texts",
    "GET /api/patients",
    "GET /api/patients/{ehc_no}",
    "GET /api/patients/{patient_id}/authorizations",
    "GET /api/patients/{patient_id}/authorizations/check",
    "GET /api/performance/improvement-stats",
    "GET /api/performance/improvements",
    "GET /api/performance/indicators",
    "GET /api/performance/orgs",
    "GET /api/pharmacy/alerts",
    "GET /api/pharmacy/purchase-orders",
    "GET /api/pharmacy/purchase-suggestions",
    "GET /api/pharmacy/stock-takes",
    "GET /api/pharmacy/stocks",
    "GET /api/pharmacy/suppliers",
    "GET /api/portal/auth/wechat/authorize",
    "GET /api/portal/health-articles",
    "GET /api/portal/me",
    "GET /api/portal/me/admissions",
    "GET /api/portal/me/admissions/{admission_id}/bill",
    "GET /api/portal/me/appointments",
    "GET /api/portal/me/archive",
    "GET /api/portal/me/bills",
    "GET /api/portal/me/consents",
    "GET /api/portal/me/contract",
    "GET /api/portal/me/corrections",
    "GET /api/portal/me/enrollments/all",
    "GET /api/portal/me/family",
    "GET /api/portal/me/notifications",
    "GET /api/portal/me/notifications/unread-count",
    "GET /api/portal/me/referrals",
    "GET /api/portal/me/referrals/all",
    "GET /api/portal/me/slots",
    "GET /api/portal/me/surgeries",
    "GET /api/portal/my-archive",
    "GET /api/portal/price-list",
    "GET /api/portal/spd/archive",
    "GET /api/portal/spd/assessments",
    "GET /api/portal/spd/consults",
    "GET /api/portal/spd/consults/{consult_id}/messages",
    "GET /api/portal/spd/edu",
    "GET /api/portal/spd/followups",
    "GET /api/portal/spd/home",
    "GET /api/portal/spd/interventions",
    "GET /api/portal/spd/journey",
    "GET /api/portal/spd/measurements",
    "GET /api/portal/spd/referrals",
    "GET /api/portal/spd/referrals/{case_id}",
    "GET /api/portal/spd/revisits",
    "GET /api/portal/spd/scales",
    "GET /api/portal/spd/scales/by-token/{qr_token}",
    "GET /api/portal/spd/service-applies",
    "GET /api/portal/spd/tasks",
    "GET /api/prescriptions",
    "GET /api/prescriptions/comment-reviews",
    "GET /api/prescriptions/comment-stats",
    "GET /api/prescriptions/rules",
    "GET /api/prescriptions/{prescription_id}/review-points",
    "GET /api/print/certs/{cert_id}",
    "GET /api/print/exam-reports/{report_id}",
    "GET /api/print/exam-requests/{request_id}",
    "GET /api/print/prescriptions/{prescription_id}",
    "GET /api/print/templates",
    "GET /api/projects",
    "GET /api/projects/stats/overview",
    "GET /api/projects/{project_id}",
    "GET /api/publichealth/events",
    "GET /api/publichealth/events/{event_id}/actions",
    "GET /api/publichealth/monitors",
    "GET /api/publichealth/reminders/{patient_id}",
    "GET /api/quality/adverse-events",
    "GET /api/quality/adverse-events-stats",
    "GET /api/quality/clinical-indicators",
    "GET /api/quality/infection-reports",
    "GET /api/quality/infection-stats",
    "GET /api/quality/record-qc",
    "GET /api/quality/record-qc-rules",
    "GET /api/quality/record-qc-stats",
    "GET /api/quality/records",
    "GET /api/quality/records/qc-summary",
    "GET /api/quality/records/{record_id}",
    "GET /api/quality/records/{record_id}/qc",
    "GET /api/rbac/modules",
    "GET /api/rbac/permissions",
    "GET /api/rbac/roles",
    "GET /api/rbac/roles/{role_id}/permissions",
    "GET /api/referrals",
    "GET /api/reports/monitoring",
    "GET /api/reports/monitoring/export",
    "GET /api/reports/operations/export",
    "GET /api/resources",
    "GET /api/resources/catalog",
    "GET /api/resources/match/or-rooms",
    "GET /api/resources/match/slots",
    "GET /api/rules",
    "GET /api/rules/catalog",
    "GET /api/rules/domains",
    "GET /api/service-requests",
    "GET /api/spd/assess-plans",
    "GET /api/spd/assessments",
    "GET /api/spd/assessments/stats",
    "GET /api/spd/call-tasks",
    "GET /api/spd/candidates",
    "GET /api/spd/case-report-tasks",
    "GET /api/spd/case-reports",
    "GET /api/spd/catalog",
    "GET /api/spd/centers",
    "GET /api/spd/consults",
    "GET /api/spd/consults/{consult_id}/messages",
    "GET /api/spd/data-sources",
    "GET /api/spd/data-sources-monitor",
    "GET /api/spd/data-sources/{source_id}/sync-logs",
    "GET /api/spd/devices",
    "GET /api/spd/edu-materials",
    "GET /api/spd/edu-pushes",
    "GET /api/spd/edu-pushes/stats",
    "GET /api/spd/enrollments",
    "GET /api/spd/enrollments/{enrollment_id}",
    "GET /api/spd/followup-records",
    "GET /api/spd/followup-records/{record_id}/context",
    "GET /api/spd/followup-rules",
    "GET /api/spd/followup-stats",
    "GET /api/spd/goods",
    "GET /api/spd/groups",
    "GET /api/spd/groups/{group_id}/members",
    "GET /api/spd/health-calendar",
    "GET /api/spd/health-prescriptions",
    "GET /api/spd/indicators",
    "GET /api/spd/indicators/{indicator_id}/usage",
    "GET /api/spd/intervention-templates",
    "GET /api/spd/interventions",
    "GET /api/spd/lifecycle-events",
    "GET /api/spd/measurements",
    "GET /api/spd/measurements/trend",
    "GET /api/spd/meta",
    "GET /api/spd/org-tree",
    "GET /api/spd/package-bindings/{binding_id}/usages",
    "GET /api/spd/path-instances",
    "GET /api/spd/path-instances/{instance_id}",
    "GET /api/spd/path-nodes/{node_id}/enter-check",
    "GET /api/spd/path-templates",
    "GET /api/spd/path-templates/{template_id}",
    "GET /api/spd/patients/{patient_id}/profile",
    "GET /api/spd/point-accounts",
    "GET /api/spd/point-accounts/me",
    "GET /api/spd/point-rules",
    "GET /api/spd/programs",
    "GET /api/spd/programs/{program_id}",
    "GET /api/spd/programs/{program_id}/targets",
    "GET /api/spd/programs/{program_id}/versions",
    "GET /api/spd/qc-samples",
    "GET /api/spd/questionnaires",
    "GET /api/spd/recalls",
    "GET /api/spd/redeems",
    "GET /api/spd/referral-rules",
    "GET /api/spd/referrals",
    "GET /api/spd/referrals-alerts",
    "GET /api/spd/referrals-stats/closure",
    "GET /api/spd/referrals/{case_id}",
    "GET /api/spd/report-instances",
    "GET /api/spd/report-instances/{instance_id}",
    "GET /api/spd/report-tasks",
    "GET /api/spd/report-templates",
    "GET /api/spd/revisits",
    "GET /api/spd/scales",
    "GET /api/spd/scales/{scale_id}",
    "GET /api/spd/scales/{scale_id}/qr.svg",
    "GET /api/spd/scores",
    "GET /api/spd/scores-analysis",
    "GET /api/spd/scores/{score_id}",
    "GET /api/spd/screenings",
    "GET /api/spd/service-applies",
    "GET /api/spd/service-packages",
    "GET /api/spd/stats/region",
    "GET /api/spd/tags",
    "GET /api/spd/tasks",
    "GET /api/spd/tasks-export",
    "GET /api/spd/tasks/summary",
    "GET /api/spd/tasks/{task_id}",
    "GET /api/spd/teams",
    "GET /api/spd/teams/{team_id}",
    "GET /api/spd/village-doctors",
    "GET /api/spd/village-doctors/{vd_id}/qr.svg",
    "GET /api/spd/workbench/admin",
    "GET /api/spd/workbench/center",
    "GET /api/spd/workbench/doctor-mobile",
    "GET /api/spd/workbench/expert",
    "GET /api/spd/workbench/health-commission",
    "GET /api/spd/workbench/team",
    "GET /api/spd/workload",
    "GET /api/staffing/dispatch-stats",
    "GET /api/staffing/secondments",
    "GET /api/surgery/requests",
    "GET /api/surgery/requests/{request_id}/record",
    "GET /api/surgery/rooms",
    "GET /api/surgery/schedules",
    "GET /api/surgery/stats",
    "GET /api/surveillance/alerts",
    "GET /api/surveillance/pathogens",
    "GET /api/surveillance/resources",
    "GET /api/surveillance/resources/readiness",
    "GET /api/surveillance/syndromes",
    "GET /api/surveys",
    "GET /api/surveys/stats",
    "GET /api/tcm-heritage/master-cases",
    "GET /api/tcm-heritage/master-cases/stats",
    "GET /api/tcm-heritage/simulations",
    "GET /api/tcm-heritage/simulations/{case_id}/attempts",
    "GET /api/tcm/constitution/spec",
    "GET /api/tcm/dispense-orders",
    "GET /api/tcm/formulas",
    "GET /api/tcm/preparation-batches",
    "GET /api/tcm/preparation-batches/expiring",
    "GET /api/tcm/techniques",
    "GET /api/telemedicine/consults",
    "GET /api/todos",
    "GET /api/users",
    "GET /api/users/role-changes",
    "GET /api/users/roles",
    "GET /api/vaccination/contraindications",
    "GET /api/vaccination/pre-check",
    "GET /api/vaccination/records",
    "GET /api/vaccine-supply/aefi",
    "GET /api/vaccine-supply/batches",
    "GET /api/vaccine-supply/batches/{batch_id}/recipients",
    "GET /api/vaccine-supply/cold-chain",
    "GET /api/vaccine-supply/expiring",
    "GET /api/vaccine-supply/stats",
    "GET /api/workflows/definitions",
    "GET /api/workflows/instances",
    "GET /api/workflows/instances/{instance_id}/history",
    "GET /api/workflows/my-tasks",
    "PATCH /api/billing/charge-items/{item_id}",
    "PATCH /api/chronic/disease-types/{type_id}",
    "PATCH /api/dataquality/rules/{rule_id}",
    "PATCH /api/disease-programs/{program_id}",
    "PATCH /api/drgs/groups/{group_id}",
    "PATCH /api/esb/endpoints/{endpoint_id}",
    "PATCH /api/esb/flows/{flow_id}",
    "PATCH /api/exams/recognition-items/{item_id}",
    "PATCH /api/exams/reports/{report_id}",
    "PATCH /api/fund/pools/{pool_id}",
    "PATCH /api/jobs/{name}",
    "PATCH /api/knowledge/{entry_id}",
    "PATCH /api/org-groups/{group_id}",
    "PATCH /api/outpatient/consent-templates/{template_id}",
    "PATCH /api/performance/indicators/{key}",
    "PATCH /api/projects/{project_id}",
    "PATCH /api/quality/record-qc-rules/{rule_id}",
    "PATCH /api/rbac/roles/{role_id}",
    "PATCH /api/referrals/{referral_id}/status",
    "PATCH /api/resources/{resource_id}",
    "PATCH /api/spd/assess-plans/{plan_id}",
    "PATCH /api/spd/case-report-tasks/{task_id}",
    "PATCH /api/spd/centers/{center_id}",
    "PATCH /api/spd/data-sources/{source_id}",
    "PATCH /api/spd/edu-materials/{material_id}",
    "PATCH /api/spd/enrollments/{enrollment_id}",
    "PATCH /api/spd/followup-records/{record_id}",
    "PATCH /api/spd/followup-rules/{rule_id}",
    "PATCH /api/spd/goods/{goods_id}",
    "PATCH /api/spd/indicators/{indicator_id}",
    "PATCH /api/spd/interventions/{intervention_id}",
    "PATCH /api/spd/path-instances/{instance_id}",
    "PATCH /api/spd/path-nodes/{node_id}",
    "PATCH /api/spd/point-rules/{rule_id}",
    "PATCH /api/spd/programs/{program_id}",
    "PATCH /api/spd/questionnaires/{q_id}",
    "PATCH /api/spd/referral-rules/{rule_id}",
    "PATCH /api/spd/report-tasks/{task_id}",
    "PATCH /api/spd/report-templates/{template_id}",
    "PATCH /api/spd/revisits/{revisit_id}",
    "PATCH /api/spd/scales/{scale_id}",
    "PATCH /api/spd/service-packages/{package_id}",
    "PATCH /api/spd/targets/{target_id}",
    "PATCH /api/spd/team-members/{member_id}",
    "PATCH /api/spd/teams/{team_id}",
    "PATCH /api/spd/village-doctors/{vd_id}",
    "PATCH /api/staffing/employees/{employee_id}/title-level",
    "PATCH /api/surveillance/resources/{resource_id}",
    "PATCH /api/users/{user_id}/role",
    "PATCH /api/vaccine-supply/aefi/{report_id}/outcome",
    "POST /api/accounting/subjects",
    "POST /api/accounting/vouchers",
    "POST /api/accounting/vouchers/{voucher_id}/post",
    "POST /api/accounting/vouchers/{voucher_id}/void",
    "POST /api/analytics/formulas",
    "POST /api/analytics/outbound-visits",
    "POST /api/appointments",
    "POST /api/appointments/blacklist",
    "POST /api/appointments/slots",
    "POST /api/appointments/slots/batch",
    "POST /api/appointments/{appointment_id}/cancel",
    "POST /api/appointments/{appointment_id}/fulfill",
    "POST /api/attachments",
    "POST /api/auth/change-password",
    "POST /api/auth/login",
    "POST /api/auth/logout",
    "POST /api/billing/charge-items",
    "POST /api/billing/charge-items/{item_id}/reprice",
    "POST /api/billing/details",
    "POST /api/billing/payments",
    "POST /api/billing/payments/{order_id}/refund",
    "POST /api/billing/reconciliation/run",
    "POST /api/billing/settlements",
    "POST /api/blood/requests",
    "POST /api/blood/requests/{request_id}/issue",
    "POST /api/blood/requests/{request_id}/review",
    "POST /api/blood/stocks",
    "POST /api/certs",
    "POST /api/checkups",
    "POST /api/chronic",
    "POST /api/chronic/disease-types",
    "POST /api/chronic/{chronic_id}/followups",
    "POST /api/consents",
    "POST /api/consents/corrections",
    "POST /api/consents/corrections/{request_id}/review",
    "POST /api/consents/{consent_id}/revoke",
    "POST /api/consultations",
    "POST /api/consultations/experts",
    "POST /api/consultations/{consultation_id}/accept",
    "POST /api/consultations/{consultation_id}/complete",
    "POST /api/consultations/{consultation_id}/decline",
    "POST /api/consultations/{consultation_id}/fee",
    "POST /api/consultations/{consultation_id}/rate",
    "POST /api/contracts",
    "POST /api/contracts/{contract_id}/services",
    "POST /api/contracts/{contract_id}/terminate",
    "POST /api/cost/allocation-rules",
    "POST /api/cost/departments",
    "POST /api/credentials",
    "POST /api/credentials/one-code",
    "POST /api/credentials/one-code/resolve",
    "POST /api/credentials/{credential_id}/recycle",
    "POST /api/credentials/{credential_id}/void",
    "POST /api/cssd/batches",
    "POST /api/cssd/batches/{batch_id}/advance",
    "POST /api/cssd/cost-items",
    "POST /api/cssd/requests",
    "POST /api/cssd/requests/{request_id}/fulfill",
    "POST /api/dataquality/rules",
    "POST /api/dictionaries/{system_code}/entries",
    "POST /api/dictionaries/{system_code}/import",
    "POST /api/disease-programs",
    "POST /api/disease-programs/enrollments/{enrollment_id}/exit",
    "POST /api/disease-programs/enrollments/{enrollment_id}/records",
    "POST /api/disease-programs/{program_id}/enrollments",
    "POST /api/drgs/groups",
    "POST /api/drgs/pre-check",
    "POST /api/education/articles",
    "POST /api/education/articles/{article_id}/publish",
    "POST /api/education/courses",
    "POST /api/education/courses/{course_id}/exam",
    "POST /api/education/courses/{course_id}/materials",
    "POST /api/education/live-sessions",
    "POST /api/education/live-sessions/{session_id}/feedback",
    "POST /api/education/live-sessions/{session_id}/finish",
    "POST /api/education/live-sessions/{session_id}/recording",
    "POST /api/education/live-sessions/{session_id}/review",
    "POST /api/education/materials/{material_id}/play",
    "POST /api/education/training-plans",
    "POST /api/education/training-plans/{plan_id}/assessments",
    "POST /api/education/training-plans/{plan_id}/cancel-enroll",
    "POST /api/education/training-plans/{plan_id}/enroll",
    "POST /api/eldercare/assessments",
    "POST /api/emergency/cases",
    "POST /api/emergency/cases/{case_id}/advance",
    "POST /api/emergency/cases/{case_id}/milestones",
    "POST /api/emergency/cases/{case_id}/rescue-outcome",
    "POST /api/emergency/cases/{case_id}/vitals",
    "POST /api/encounters",
    "POST /api/esb/endpoints",
    "POST /api/esb/endpoints/{endpoint_id}/rotate-token",
    "POST /api/esb/flows",
    "POST /api/esb/flows/{code}/run",
    "POST /api/esb/messages",
    "POST /api/esb/messages/{message_id}/process",
    "POST /api/exams",
    "POST /api/exams/recognition-items",
    "POST /api/exams/reports/{report_id}/acknowledge",
    "POST /api/exams/reports/{report_id}/resolve",
    "POST /api/exams/resources",
    "POST /api/exams/templates",
    "POST /api/exams/{request_id}/claim",
    "POST /api/exams/{request_id}/report",
    "POST /api/exams/{request_id}/sample/advance",
    "POST /api/followups",
    "POST /api/followups/{task_id}/cancel",
    "POST /api/followups/{task_id}/complete",
    "POST /api/fund/pools",
    "POST /api/fund/pools/{pool_id}/distribute",
    "POST /api/fund/pools/{pool_id}/periods",
    "POST /api/fund/pools/{pool_id}/prepayments",
    "POST /api/fund/pools/{pool_id}/settle",
    "POST /api/homevisits",
    "POST /api/homevisits/{order_id}/cancel",
    "POST /api/homevisits/{order_id}/complete",
    "POST /api/homevisits/{order_id}/dispatch",
    "POST /api/infectious/cases",
    "POST /api/inpatient/admissions",
    "POST /api/inpatient/admissions/{admission_id}/case-summary",
    "POST /api/inpatient/admissions/{admission_id}/discharge",
    "POST /api/inpatient/admissions/{admission_id}/nursing-records",
    "POST /api/inpatient/admissions/{admission_id}/progress-notes",
    "POST /api/inpatient/admissions/{admission_id}/transfer",
    "POST /api/inpatient/admissions/{admission_id}/vitals",
    "POST /api/inpatient/beds",
    "POST /api/inpatient/handovers",
    "POST /api/inpatient/orders",
    "POST /api/inpatient/orders/{order_id}/stop",
    "POST /api/inpatient/wards",
    "POST /api/insurance/dual-channel",
    "POST /api/insurance/dual-channel/{app_id}/review",
    "POST /api/insurance/referral-certs/{referral_id}",
    "POST /api/insurance/settlements",
    "POST /api/insurance/special-diseases",
    "POST /api/insurance/special-diseases/{app_id}/review",
    "POST /api/integration/fhir/DiagnosticReport",
    "POST /api/integration/fhir/Encounter",
    "POST /api/integration/fhir/Observation",
    "POST /api/integration/fhir/Patient",
    "POST /api/integration/hl7v2/adt",
    "POST /api/integration/hl7v2/oru",
    "POST /api/integration/hl7v2/patient",
    "POST /api/jobs/{name}/run",
    "POST /api/knowledge",
    "POST /api/materials/consumables",
    "POST /api/materials/consumables/{barcode}/use",
    "POST /api/materials/purchases",
    "POST /api/materials/purchases/{purchase_id}/approve",
    "POST /api/materials/purchases/{purchase_id}/contract",
    "POST /api/materials/purchases/{purchase_id}/receive",
    "POST /api/maternal/children",
    "POST /api/maternal/children/{child_id}/high-risk",
    "POST /api/maternal/children/{child_id}/screenings",
    "POST /api/maternal/children/{child_id}/visits",
    "POST /api/maternal/records",
    "POST /api/maternal/records/{record_id}/close",
    "POST /api/maternal/records/{record_id}/delivery",
    "POST /api/maternal/records/{record_id}/visits",
    "POST /api/maternal/screenings",
    "POST /api/maternal/women-health",
    "POST /api/medication/shortages",
    "POST /api/medication/shortages/{shortage_id}/advance",
    "POST /api/medication/shortages/{shortage_id}/close",
    "POST /api/medwaste",
    "POST /api/medwaste/locations",
    "POST /api/medwaste/locations/{location_id}/reactivate",
    "POST /api/medwaste/{waste_id}/handover",
    "POST /api/medwaste/{waste_id}/store",
    "POST /api/mgmt/assets",
    "POST /api/mgmt/assets/{asset_id}/movements",
    "POST /api/mgmt/assets/{asset_id}/scrap",
    "POST /api/mgmt/assets/{asset_id}/transfer",
    "POST /api/mgmt/budgets",
    "POST /api/mgmt/departments",
    "POST /api/mgmt/docs",
    "POST /api/mgmt/docs/{doc_id}/publish",
    "POST /api/mgmt/employees",
    "POST /api/mgmt/employees/{employee_id}/changes",
    "POST /api/mgmt/employees/{employee_id}/department",
    "POST /api/mgmt/finance",
    "POST /api/mgmt/params",
    "POST /api/mgmt/payroll",
    "POST /api/mgmt/qc",
    "POST /api/mgmt/rosters",
    "POST /api/mgmt/secondments",
    "POST /api/mgmt/secondments/{secondment_id}/end",
    "POST /api/mgmt/staff-contracts",
    "POST /api/notifications/read-all",
    "POST /api/notifications/{notification_id}/read",
    "POST /api/org-groups",
    "POST /api/org-groups/{group_id}/members",
    "POST /api/organizations",
    "POST /api/outpatient/consent-templates",
    "POST /api/outpatient/consents",
    "POST /api/outpatient/consents/{consent_id}/refuse",
    "POST /api/outpatient/consents/{consent_id}/sign",
    "POST /api/outpatient/encounters/{encounter_id}/nursing-records",
    "POST /api/outpatient/encounters/{encounter_id}/treatments",
    "POST /api/pathology/specimens",
    "POST /api/pathology/specimens/{specimen_id}/advance",
    "POST /api/pathology/specimens/{specimen_id}/receive",
    "POST /api/pathology/specimens/{specimen_id}/reject",
    "POST /api/patients",
    "POST /api/patients/{patient_id}/authorizations",
    "POST /api/patients/{patient_id}/authorizations/{auth_id}/revoke",
    "POST /api/performance/improvements",
    "POST /api/performance/improvements/{task_id}/progress",
    "POST /api/performance/improvements/{task_id}/verify",
    "POST /api/pharmacy/purchase-orders",
    "POST /api/pharmacy/purchase-orders/{order_id}/approve",
    "POST /api/pharmacy/purchase-orders/{order_id}/receive",
    "POST /api/pharmacy/stock-takes",
    "POST /api/pharmacy/stocks",
    "POST /api/pharmacy/suppliers",
    "POST /api/pharmacy/transfers",
    "POST /api/portal/auth/bind-phone",
    "POST /api/portal/auth/bind-wechat",
    "POST /api/portal/auth/logout",
    "POST /api/portal/auth/realname",
    "POST /api/portal/auth/sms/code",
    "POST /api/portal/auth/sms/login",
    "POST /api/portal/auth/wechat/login",
    "POST /api/portal/me/appointments",
    "POST /api/portal/me/appointments/{appointment_id}/cancel",
    "POST /api/portal/me/consents",
    "POST /api/portal/me/corrections",
    "POST /api/portal/me/family",
    "POST /api/portal/me/notifications/{notification_id}/read",
    "POST /api/portal/me/surveys",
    "POST /api/portal/my-archive",
    "POST /api/portal/spd/consults",
    "POST /api/portal/spd/edu/{push_id}/read",
    "POST /api/portal/spd/followups/{record_id}/self-answer",
    "POST /api/portal/spd/interventions/{intervention_id}/feedback",
    "POST /api/portal/spd/measurements",
    "POST /api/portal/spd/screenings",
    "POST /api/portal/spd/service-applies",
    "POST /api/portal/spd/tasks/{task_id}/attachments",
    "POST /api/portal/spd/tasks/{task_id}/submit",
    "POST /api/portal/surveys",
    "POST /api/prescriptions",
    "POST /api/prescriptions/rules",
    "POST /api/prescriptions/rules/import",
    "POST /api/prescriptions/rules/{drug_code}/reactivate",
    "POST /api/prescriptions/{prescription_id}/comment-review",
    "POST /api/prescriptions/{prescription_id}/review",
    "POST /api/projects",
    "POST /api/projects/milestones/{milestone_id}/done",
    "POST /api/projects/milestones/{milestone_id}/reopen",
    "POST /api/projects/{project_id}/milestones",
    "POST /api/publichealth/events",
    "POST /api/publichealth/events/{event_id}/actions",
    "POST /api/publichealth/events/{event_id}/close",
    "POST /api/publichealth/monitors",
    "POST /api/quality/adverse-events",
    "POST /api/quality/adverse-events/{event_id}/rectify",
    "POST /api/quality/adverse-events/{event_id}/review",
    "POST /api/quality/infection-reports",
    "POST /api/quality/infection-reports/{report_id}/verify",
    "POST /api/quality/record-qc",
    "POST /api/quality/records",
    "POST /api/rbac/roles",
    "POST /api/rbac/roles/{role_id}/permissions",
    "POST /api/referrals",
    "POST /api/resources",
    "POST /api/resources/{resource_id}/publish",
    "POST /api/resources/{resource_id}/withdraw",
    "POST /api/rules",
    "POST /api/rules/evaluate",
    "POST /api/spd/assess-plans",
    "POST /api/spd/assessments",
    "POST /api/spd/call-tasks",
    "POST /api/spd/call-tasks/{task_id}/result",
    "POST /api/spd/candidates/distribute",
    "POST /api/spd/candidates/{candidate_id}/claim",
    "POST /api/spd/candidates/{candidate_id}/status",
    "POST /api/spd/case-report-tasks",
    "POST /api/spd/case-reports",
    "POST /api/spd/case-reports/{report_id}/handle",
    "POST /api/spd/centers",
    "POST /api/spd/consults/{consult_id}/close",
    "POST /api/spd/consults/{consult_id}/reply",
    "POST /api/spd/consults/{consult_id}/to-followup",
    "POST /api/spd/data-sources",
    "POST /api/spd/data-sources/{source_id}/sync-logs",
    "POST /api/spd/devices",
    "POST /api/spd/devices/{device_id}/bind",
    "POST /api/spd/edu-materials",
    "POST /api/spd/edu-pushes",
    "POST /api/spd/enrollments",
    "POST /api/spd/enrollments/{enrollment_id}/lifecycle",
    "POST /api/spd/enrollments/{enrollment_id}/packages",
    "POST /api/spd/followup-plans",
    "POST /api/spd/followup-plans/auto-match",
    "POST /api/spd/followup-records/{record_id}/execute",
    "POST /api/spd/followup-rules",
    "POST /api/spd/goods",
    "POST /api/spd/groups",
    "POST /api/spd/groups/{group_id}/members",
    "POST /api/spd/health-prescriptions",
    "POST /api/spd/indicators",
    "POST /api/spd/intervention-templates",
    "POST /api/spd/interventions",
    "POST /api/spd/lifecycle-events/{event_id}/confirm",
    "POST /api/spd/measurements",
    "POST /api/spd/measurements/batch",
    "POST /api/spd/package-bindings/{binding_id}/unbind",
    "POST /api/spd/package-bindings/{binding_id}/usages",
    "POST /api/spd/path-instances",
    "POST /api/spd/path-instances/{instance_id}/advance",
    "POST /api/spd/path-templates",
    "POST /api/spd/path-templates/{template_id}/copy",
    "POST /api/spd/path-templates/{template_id}/nodes",
    "POST /api/spd/path-templates/{template_id}/status",
    "POST /api/spd/point-accounts/signin",
    "POST /api/spd/point-rules",
    "POST /api/spd/programs",
    "POST /api/spd/programs/{program_id}/targets",
    "POST /api/spd/qc-samples/plan",
    "POST /api/spd/qc-samples/{sample_id}/result",
    "POST /api/spd/questionnaires",
    "POST /api/spd/recalls/{recall_id}/progress",
    "POST /api/spd/redeems",
    "POST /api/spd/redeems/verify",
    "POST /api/spd/referral-rules",
    "POST /api/spd/referral-rules/check",
    "POST /api/spd/referrals",
    "POST /api/spd/referrals/{case_id}/arrive",
    "POST /api/spd/referrals/{case_id}/down",
    "POST /api/spd/referrals/{case_id}/receive-followup",
    "POST /api/spd/referrals/{case_id}/review",
    "POST /api/spd/referrals/{case_id}/withdraw",
    "POST /api/spd/report-instances",
    "POST /api/spd/report-tasks",
    "POST /api/spd/report-templates",
    "POST /api/spd/revisits",
    "POST /api/spd/scales",
    "POST /api/spd/scales/{scale_id}/disable",
    "POST /api/spd/scales/{scale_id}/publish",
    "POST /api/spd/scores/run",
    "POST /api/spd/screenings",
    "POST /api/spd/screenings/auto-run",
    "POST /api/spd/screenings/{screening_id}/review",
    "POST /api/spd/service-applies/{apply_id}/handle",
    "POST /api/spd/service-packages",
    "POST /api/spd/tags",
    "POST /api/spd/tasks",
    "POST /api/spd/tasks/batch",
    "POST /api/spd/tasks/{task_id}/assign",
    "POST /api/spd/tasks/{task_id}/claim",
    "POST /api/spd/tasks/{task_id}/complete",
    "POST /api/spd/tasks/{task_id}/escalate",
    "POST /api/spd/tasks/{task_id}/review",
    "POST /api/spd/tasks/{task_id}/submit",
    "POST /api/spd/tasks/{task_id}/urge",
    "POST /api/spd/teams",
    "POST /api/spd/teams/{team_id}/members",
    "POST /api/spd/village-doctors",
    "POST /api/spd/village-doctors/batch",
    "POST /api/staffing/secondments",
    "POST /api/staffing/secondments/{secondment_id}/end",
    "POST /api/surgery/requests",
    "POST /api/surgery/requests/{request_id}/approve",
    "POST /api/surgery/requests/{request_id}/record",
    "POST /api/surgery/requests/{request_id}/schedule",
    "POST /api/surgery/rooms",
    "POST /api/surveillance/pathogens",
    "POST /api/surveillance/resources",
    "POST /api/surveillance/syndromes",
    "POST /api/surveys",
    "POST /api/tcm-heritage/master-cases",
    "POST /api/tcm-heritage/master-cases/{case_id}/publish",
    "POST /api/tcm-heritage/master-cases/{case_id}/unpublish",
    "POST /api/tcm-heritage/simulations",
    "POST /api/tcm-heritage/simulations/{case_id}/attempts",
    "POST /api/tcm/assist-diagnosis",
    "POST /api/tcm/constitution",
    "POST /api/tcm/dispense-orders",
    "POST /api/tcm/dispense-orders/{order_id}/advance",
    "POST /api/tcm/formulas",
    "POST /api/tcm/preparation-batches",
    "POST /api/tcm/preparation-batches/{batch_id}/release",
    "POST /api/tcm/techniques",
    "POST /api/telemedicine/consults",
    "POST /api/telemedicine/consults/{consult_id}/close",
    "POST /api/telemedicine/consults/{consult_id}/reply",
    "POST /api/triage/suggest",
    "POST /api/users",
    "POST /api/vaccination/contraindications",
    "POST /api/vaccination/contraindications/{contra_id}/lift",
    "POST /api/vaccination/records",
    "POST /api/vaccine-supply/aefi",
    "POST /api/vaccine-supply/batches",
    "POST /api/vaccine-supply/batches/{batch_id}/freeze",
    "POST /api/vaccine-supply/batches/{batch_id}/unfreeze",
    "POST /api/vaccine-supply/cold-chain",
    "POST /api/vaccine-supply/cold-chain/{record_id}/handle",
    "POST /api/workflows/definitions",
    "POST /api/workflows/instances",
    "POST /api/workflows/instances/{instance_id}/advance",
    "POST /api/workflows/instances/{instance_id}/cancel",
    "PUT /api/print/templates",
}

#: 当前 ORM 类名快照（246 个）。由真实应用生成，勿手写。
SNAPSHOT_MODELS = {
    "AccessLog",
    "AccountSubject",
    "AdminProject",
    "Admission",
    "AdverseEvent",
    "AefiReport",
    "Appointment",
    "AppointmentSlot",
    "ArchiveAuthorization",
    "Asset",
    "AssetMovement",
    "Attachment",
    "AuditLog",
    "Bed",
    "BillDetail",
    "BloodStock",
    "Budget",
    "CaseSummary",
    "ChargeItem",
    "ChargePriceChange",
    "ChildRecord",
    "ChildVisit",
    "ChronicDiseaseType",
    "ChronicPatient",
    "CodeEntry",
    "CodeSystem",
    "ColdChainRecord",
    "ConsentRecord",
    "ConsentTemplate",
    "ConsentText",
    "ConsultExpert",
    "Consultation",
    "ContractService",
    "CorrectionRequest",
    "CostAllocationRule",
    "Course",
    "CourseMaterial",
    "CriticalAction",
    "CssdCostItem",
    "CssdRequest",
    "DeliveryRecord",
    "Department",
    "DepartmentCost",
    "DiseaseEnrollment",
    "DiseasePathRecord",
    "DiseaseProgram",
    "DrgGroup",
    "DrugRule",
    "DrugShortage",
    "DrugStock",
    "DualChannelApp",
    "DutyRoster",
    "ElderlyAssessment",
    "EmergencyCase",
    "EmergencyMilestone",
    "EmergencyResource",
    "EmergencyVital",
    "Employee",
    "EmployeeChange",
    "Encounter",
    "EsbEndpoint",
    "EsbFlow",
    "EsbFlowRun",
    "EsbMessage",
    "ExamReport",
    "ExamRequest",
    "ExamResource",
    "ExchangeLog",
    "FamilyDoctorContract",
    "FinanceEntry",
    "FollowUp",
    "FollowupTask",
    "FundDistribution",
    "FundPeriod",
    "FundPool",
    "FundPrepayment",
    "FundSettlement",
    "HealthArticle",
    "HealthMonitorRecord",
    "HighValueConsumable",
    "HomeVisitOrder",
    "ImprovementTask",
    "InfectionReport",
    "InfectiousCase",
    "InfectiousDisease",
    "InformedConsent",
    "InpatientOrder",
    "InsuranceSettlement",
    "JobRun",
    "KnowledgeEntry",
    "LiveFeedback",
    "LiveSession",
    "MaterialPurchase",
    "MaternalRecord",
    "MaternalVisit",
    "MedicalCert",
    "MedicalRecord",
    "MedicalWaste",
    "NewbornScreening",
    "Notification",
    "NursingRecord",
    "OfficialDoc",
    "OnlineConsult",
    "OperatingRoom",
    "OrgGroup",
    "OrgGroupMember",
    "Organization",
    "OutboundVisit",
    "PathogenMonitor",
    "PathologySpecimen",
    "Patient",
    "PaymentOrder",
    "PayrollRecord",
    "PerformanceFormula",
    "PerformanceIndicator",
    "Permission",
    "PhEventAction",
    "PhysicalExam",
    "PrenatalScreening",
    "Prescription",
    "PrescriptionComment",
    "PrescriptionItem",
    "PrintTemplate",
    "ProgressNote",
    "ProjectMilestone",
    "PublicHealthEvent",
    "PurchaseOrder",
    "QcRecord",
    "QcRule",
    "RecognitionItem",
    "ReconciliationBatch",
    "ReconciliationDiff",
    "RecordQc",
    "RecordQcRule",
    "Referral",
    "ReferralCert",
    "ReportRevision",
    "ReportTemplate",
    "ResidentAccount",
    "ResidentFamilyMember",
    "Resource",
    "Role",
    "RoleChangeLog",
    "RolePermission",
    "RuleDefinition",
    "SatisfactionSurvey",
    "ScheduledJob",
    "Secondment",
    "ServiceBlacklist",
    "Settlement",
    "ShiftHandover",
    "SimulationAttempt",
    "SimulationCase",
    "SmsCode",
    "SpdAssessPlan",
    "SpdAssessment",
    "SpdCallTask",
    "SpdCandidate",
    "SpdCaseReport",
    "SpdCaseReportTask",
    "SpdCenter",
    "SpdConsult",
    "SpdConsultMessage",
    "SpdDataSource",
    "SpdDevice",
    "SpdEduMaterial",
    "SpdEduPush",
    "SpdEnrollment",
    "SpdFollowupRecord",
    "SpdFollowupRule",
    "SpdGoods",
    "SpdGroup",
    "SpdGroupMember",
    "SpdHealthPrescription",
    "SpdIndicator",
    "SpdIntervention",
    "SpdInterventionTemplate",
    "SpdLifecycleEvent",
    "SpdMeasurement",
    "SpdPackageBinding",
    "SpdPackageUsage",
    "SpdPathInstance",
    "SpdPathNode",
    "SpdPathTemplate",
    "SpdPointAccount",
    "SpdPointRecord",
    "SpdPointRule",
    "SpdProgram",
    "SpdProgramVersion",
    "SpdQcSample",
    "SpdQuestionnaire",
    "SpdRecall",
    "SpdRedeem",
    "SpdReferralCase",
    "SpdReferralRule",
    "SpdReferralStep",
    "SpdReportInstance",
    "SpdReportTask",
    "SpdReportTemplate",
    "SpdRevisit",
    "SpdScale",
    "SpdScore",
    "SpdScreening",
    "SpdServiceApply",
    "SpdServicePackage",
    "SpdSignin",
    "SpdSyncLog",
    "SpdTag",
    "SpdTarget",
    "SpdTask",
    "SpdTeam",
    "SpdTeamMember",
    "SpdVillageDoctor",
    "SpecialDiseaseApp",
    "StaffContract",
    "SterilizationBatch",
    "StockTake",
    "StockTransfer",
    "Supplier",
    "SurgeryRecord",
    "SurgeryRequest",
    "SurgerySchedule",
    "SyndromeMonitor",
    "SystemParam",
    "TcmDispenseOrder",
    "TcmFormula",
    "TcmMasterCase",
    "TcmPreparationBatch",
    "TcmTechnique",
    "TrainingAssessment",
    "TrainingEnrollment",
    "TrainingPlan",
    "TrainingRecord",
    "TransfusionRequest",
    "TreatmentRecord",
    "User",
    "VaccinationRecord",
    "VaccineBatch",
    "VaccineContraindication",
    "VisitCredential",
    "VitalSignRecord",
    "Voucher",
    "VoucherEntry",
    "Ward",
    "WasteLocation",
    "WomenHealthRecord",
    "WorkflowDefinition",
    "WorkflowInstance",
    "WorkflowTransition",
}



def _walk(routes):
    """递归展开路由树，穿过 `_IncludedRouter` 这类运行期封装。"""
    for route in routes:
        if isinstance(route, APIRoute):
            yield route
        # include_router 的结果：真正的子路由挂在 original_router 上
        original = getattr(route, "original_router", None)
        if original is not None and getattr(original, "routes", None):
            yield from _walk(original.routes)
        elif isinstance(route, APIRouter) and getattr(route, "routes", None):
            yield from _walk(route.routes)


def _current_endpoints() -> set[str]:
    """当前应用真正暴露的 `METHOD /path` 集合（只看 /api，且只看进 schema 的）。

    为什么要按 `include_in_schema` 过滤：测试会往这个共享的 `app` 上挂脚手架路由
    （`tests/test_p0_fixes.py` 在导入时注册 `POST /api/_test/boom` 来触发 500，
    验错误处理与审计留痕），且挂上就不摘。于是本用例单跑是绿的、全量套件里却红——
    差的正是那条脚手架。

    按 `include_in_schema` 过滤而不是按 `/api/_test/` 前缀特判：**产品端点里
    没有一条设 `include_in_schema=False`**（已核过），所以这个标志恰好把
    "对外承诺的接口面"与"测试临时挂的东西"分得干干净净，而且语义上就是
    "这条算不算公开契约"——正是本守卫要量的东西。
    """
    return {
        f"{method} {route.path}"
        for route in _walk(app.routes)
        if route.path.startswith("/api") and route.include_in_schema
        for method in sorted(route.methods - {"HEAD", "OPTIONS"})
    }


def _current_models() -> set[str]:
    return {
        cls.__name__
        for cls in Base.registry._class_registry.values()
        if hasattr(cls, "__tablename__")
    }


def test_遍历本身没瞎():
    """守卫的守卫：遍历方式失效时，上面两条会变成"永远绿"，必须先炸在这里。"""
    count = len(_current_endpoints())
    assert count >= MIN_SANE_ENDPOINTS, (
        f"只遍历到 {count} 个端点，远低于下限 {MIN_SANE_ENDPOINTS}——"
        "多半是 FastAPI 的路由封装变了、`_walk` 穿不过去了。"
        "先修遍历，别改下限，否则零漂移守卫就成了摆设。"
    )


def test_端点集合零漂移():
    current = _current_endpoints()
    missing = SNAPSHOT_ENDPOINTS - current
    added = current - SNAPSHOT_ENDPOINTS
    assert not missing, (
        f"以下端点消失了（{len(missing)} 个）——搬路由时漏了，或 path 被改了：\n  "
        + "\n  ".join(sorted(missing))
    )
    assert not added, (
        f"以下端点是新增的（{len(added)} 个）。有意新增请更新 SNAPSHOT_ENDPOINTS 并在 "
        f"PR 里说明；**纯重构 PR 里出现新增就是搬错了**：\n  "
        + "\n  ".join(sorted(added))
    )


def test_模型名字集合零漂移():
    current = _current_models()
    missing = SNAPSHOT_MODELS - current
    added = current - SNAPSHOT_MODELS
    assert not missing, (
        f"以下 ORM 类从 Base 注册表消失了（{len(missing)} 个）——拆包时漏了重导出，"
        f"建表会**静默少表**：\n  " + "\n  ".join(sorted(missing))
    )
    assert not added, (
        f"以下 ORM 类是新增的（{len(added)} 个）。有意新增请更新 SNAPSHOT_MODELS "
        f"并在 PR 里说明：\n  " + "\n  ".join(sorted(added))
    )


# ---------------------------------------------------------------------------
# ADR-0008 拆包的附加守卫
# ---------------------------------------------------------------------------


def test_拆包后导入路径不变():
    """拆包对调用方必须透明：`from .routers import config` 再用 `config.router`。

    ADR-0008 选方案 B（拆包 + `__init__.py` 重导出）而不是方案 C（改上千处 import），
    理由就是"改 import 换不来任何功能收益"。这条钉住那个承诺。
    """
    from app.spd.routers import config

    assert hasattr(config, "router"), "config.router 必须还在，否则调用方全断"
    assert config.router.prefix == "/api/spd"


def test_配置域子模块的注册顺序与原分节一致():
    """路由靠 import 时的装饰器注册，顺序决定 FastAPI 的匹配优先级。

    乱序**不会报错**，只会让某些路径悄悄匹配到别的处理函数上——正是那种
    "测试全绿但线上行为变了"的改动。所以顺序本身要有人盯着。
    """
    import inspect

    from app.spd.routers import config

    source = inspect.getsource(config)
    expected = ["catalog", "paths", "scales", "teams", "devices", "centers"]
    line = next(l for l in source.splitlines() if l.startswith("from . import "))
    actual = [m.strip() for m in line.removeprefix("from . import ").split("#")[0].split(",")]
    assert actual == expected, (
        f"子模块导入顺序变了：{actual}，应为 {expected}（= 原文件的分节顺序）"
    )


def test_models拆包后导入路径不变():
    """全仓库上千处 `from ..models import X` 必须照旧可用。

    ADR-0008 选方案 B（拆包 + `__init__` 重导出）而不是改所有 import，
    理由就是后者换不来任何功能收益。这条钉住那个承诺。
    """
    from app import models

    # 各域各抽一个，外加子系统模型与两个列约定
    for name in ("User", "Patient", "Encounter", "Prescription", "Admission",
                 "ChronicPatient", "MaternalRecord", "FamilyDoctorContract",
                 "Voucher", "Asset", "Employee", "AdverseEvent", "Attachment",
                 "ResidentAccount", "EmergencyCase", "SpdEnrollment",
                 "Money", "utcnow"):
        assert hasattr(models, name), f"app.models.{name} 不见了——调用方会直接 ImportError"


def test_models各域模块都被__init__导入():
    """漏掉一个域 = 那批表不进 `Base.metadata` = 建库静默少表。

    这是拆 models 最危险的失败模式：**不报错**。上面的 SNAPSHOT_MODELS
    会兜住，这条再把原因说清楚，省得下次有人对着"少了 12 个类"发愣。
    """
    import pkgutil

    from app import models

    on_disk = {
        m.name for m in pkgutil.iter_modules(models.__path__)
        if not m.name.startswith("_")
    }
    source = (Path(models.__file__)).read_text(encoding="utf-8")
    imported = {
        line.removeprefix("from .").split(" import")[0]
        for line in source.splitlines()
        if line.startswith("from .") and " import *" in line
    }
    assert on_disk <= imported, (
        f"这些域模块躺在包里却没被 __init__ 导入：{sorted(on_disk - imported)}——"
        "它们的表不会进 Base.metadata，建库时会静默少表"
    )
